---

roles:

  - name: idiv_biodiversity.nslcd
    src: https://github.com/idiv-biodiversity/ansible-role-nslcd

  - name: idiv_biodiversity.nsswitch
    src: https://github.com/idiv-biodiversity/ansible-role-nsswitch

...
