---

- name: configure /etc/pam.d/system-auth
  ansible.builtin.template:
    src: system-auth.j2
    dest: /etc/pam.d/system-auth
    owner: root
    group: root
    mode: 0644
  become: yes

- name: configure /etc/pam.d/login
  ansible.builtin.template:
    src: login.j2
    dest: /etc/pam.d/login
    owner: root
    group: root
    mode: 0644
  become: yes

...
